<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Lenovo-PC" ignored="0" name="Surefire test" tests="23" failures="0" timestamp="2020-04-23T14:06:59 IST" time="19.31" errors="0">
  <testcase name="loginTest on loginTest(com.cts.controller.AuthControllerTest)" time="9.632" classname="com.cts.controller.AuthControllerTest"/>
  <testcase name="createUserTest on createUserTest(com.cts.controller.AuthControllerTest)" time="9.642" classname="com.cts.controller.AuthControllerTest"/>
  <testcase name="testCreateStudentSuccess on testCreateStudentSuccess(com.cts.controller.StudentControllerTest)" time="2.659" classname="com.cts.controller.StudentControllerTest"/>
  <testcase name="handleInternalServerExceptionTest on handleInternalServerExceptionTest(com.cts.exception.CustomExceptionHandlerTest)" time="0.75" classname="com.cts.exception.CustomExceptionHandlerTest"/>
  <testcase name="handleAllExceptionTest on handleAllExceptionTest(com.cts.exception.CustomExceptionHandlerTest)" time="0.755" classname="com.cts.exception.CustomExceptionHandlerTest"/>
  <testcase name="handleRecordNotFoundExceptionTest on handleRecordNotFoundExceptionTest(com.cts.exception.CustomExceptionHandlerTest)" time="0.769" classname="com.cts.exception.CustomExceptionHandlerTest"/>
  <testcase name="methodArgumentNotValidTest on methodArgumentNotValidTest(com.cts.exception.CustomExceptionHandlerTest)" time="0.783" classname="com.cts.exception.CustomExceptionHandlerTest"/>
  <testcase name="errorResponsetest on errorResponsetest(com.cts.exception.ErrorResponseTest)" time="0.006" classname="com.cts.exception.ErrorResponseTest"/>
  <testcase name="test on test(com.cts.exception.InternalServerErrorTest)" time="0.009" classname="com.cts.exception.InternalServerErrorTest"/>
  <testcase name="test on test(com.cts.exception.RecordNotFoundExceptionTest)" time="0.006" classname="com.cts.exception.RecordNotFoundExceptionTest"/>
  <testcase name="loginTest on loginTest(com.cts.repository.AuthRepositoryTest)" time="0.033" classname="com.cts.repository.AuthRepositoryTest"/>
  <testcase name="createUserTest on createUserTest(com.cts.repository.AuthRepositoryTest)" time="0.039" classname="com.cts.repository.AuthRepositoryTest"/>
  <testcase name="loginTestFailure on loginTestFailure(com.cts.repository.AuthRepositoryTest)" time="0.049" classname="com.cts.repository.AuthRepositoryTest"/>
  <testcase name="loginTest on loginTest(com.cts.service.AuthServiceTest)" time="0.033" classname="com.cts.service.AuthServiceTest"/>
  <testcase name="createUserTest on createUserTest(com.cts.service.AuthServiceTest)" time="0.039" classname="com.cts.service.AuthServiceTest"/>
  <testcase name="contextLoads on contextLoads(com.cts.ShoppingcartApplicationTest)" time="1.636" classname="com.cts.ShoppingcartApplicationTest"/>
  <testcase name="writeExcel on writeExcel(com.cts.util.RWExcelFileAuthTest)" time="2.143" classname="com.cts.util.RWExcelFileAuthTest"/>
  <testcase name="readExcelTest on readExcelTest(com.cts.util.RWExcelFileAuthTest)" time="2.204" classname="com.cts.util.RWExcelFileAuthTest"/>
  <testcase name="writeExcelException on writeExcelException(com.cts.util.RWExcelFileAuthTest)" time="2.21" classname="com.cts.util.RWExcelFileAuthTest"/>
  <testcase name="readExcelTestElse on readExcelTestElse(com.cts.util.RWExcelFileAuthTest)" time="2.248" classname="com.cts.util.RWExcelFileAuthTest"/>
  <testcase name="readExcelTestException on readExcelTestException(com.cts.util.RWExcelFileAuthTest)" time="2.251" classname="com.cts.util.RWExcelFileAuthTest"/>
  <testcase name="readExcelTest on readExcelTest(com.cts.util.RWExcelFileTest)" time="0.14" classname="com.cts.util.RWExcelFileTest"/>
  <testcase name="writeExcelTest on writeExcelTest(com.cts.util.RWExcelFileTest)" time="0.396" classname="com.cts.util.RWExcelFileTest"/>
</testsuite> <!-- Surefire test -->
